name: "CI-linux"
on:
  pull_request:
  push:
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (clean environment)
        uses: actions/checkout@v2.3.4
      - name: Use Nix (flakes, nixpkgs-unstable)
        uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
          extra_nix_config: |
            experimental-features = nix-command flakes
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Use Cachix (Never build software more than once)
        uses: cachix/cachix-action@v10
        with:
          name: nokxpkgs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build Linux Release (run tests)
        run: nix build .#hydraJobs.release.x86_64-linux --show-trace
