name: "nokxpkgs"
on:
  pull_request:
  push:
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
      - run: nix-build . -A hydraJobs.release.x86_64-linux --no-out-link --show-trace
  macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
      - run: nix-build . -A hydraJobs.release.x86_64-darwin --no-out-link --show-trace
