name: "NOKXPKGS"
on:
  pull_request:
  push:
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
      - run: nix-build . -A all-nokx --no-out-link
  macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
      - run: nix-build . -A all-nokx --no-out-link
